### ISSUE TITLE
sailed.io 0.10.8 regression build failure

### ISSUE THREAD

**Issue by chenrui333** [kovshenin/sail#109]
👋 While trying to [upgrade rust to 1.77.0](https://github.com/Homebrew/homebrew-core/pull/166865), I noticed that the sailed.io 0.10.8 regression build failed. And then I [did a formula rebuild](https://github.com/Homebrew/homebrew-core/pull/167272), looks like it still failed as well. Any ideas about the root cause? Thanks!

**Comment by chenrui333** [comment]
This is the error build log

```
  Traceback (most recent call last):
    File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/private/tmp/pip-build-env-evizj83s/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/tmp/pip-build-env-evizj83s/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/private/tmp/pip-build-env-evizj83s/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
      super().run_setup(setup_script=setup_script)
    File "/private/tmp/pip-build-env-evizj83s/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 5, in <module>
    File "/private/tmp/sail-20240327-7357-cnmuxb/sailed.io-0.10.8/sail/__init__.py", line 15, in <module>
      import paramiko
  ModuleNotFoundError: No module named 'paramiko'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/local/Cellar/sail/0.10.8_3/libexec/bin/python /usr/local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /private/tmp/tmpzywdw3mx
  cwd: /private/tmp/sail-20240327-7357-cnmuxb/sailed.io-0.10.8
  Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error
```
